<?php
namespace app\admin\controller;
class Person extends Base
{
    protected $model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model=model('driver');
    }

    public function dataList()
    {
        $where=$this->buildWhere(['company','name1:like']);
        $list=$this->model->data_list($where);
        $company=model('company')->selectList();
        $this->assign('company', $company);
        $this->assign('list', $list);
        return $this->fetch('list');
    }

    public function add(){
        if($this->request->isPost()){
            $data=input();
            $file = request()->file('imgurl');
            // 移动到框架应用根目录/public/uploads/ 目录下
            if($file){
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads');
                if($info){
                    $data['imgurl']=$info->getSaveName();
                }else{
                    // 上传失败获取错误信息
                    $this->error($file->getError());
                }
            }
            $result=$this->model->add($data);
            $this->updateResult($result);
        }else{
            return $this->fetch();
        }
    }

    public function edit(){
        if($this->request->isPost()){
            $data=input();
            $file = request()->file('imgurl');
            // 移动到框架应用根目录/public/uploads/ 目录下
            if($file){
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads');
                if($info){
                    $data['imgurl']=$info->getSaveName();
                }else{
                    // 上传失败获取错误信息
                    $this->error($file->getError());
                }
            }
            $result=$this->model->edit($data);
            $this->updateResult($result,'保存成功','dataList');
        }else{
            $id=input('id');
            $data=$this->model->getOne($id);
            if(!$data){
                $this->error($this->model->getError());
            };
            $this->assign('data', $data);
            return $this->fetch();
        }
    }

    public function del($id=''){
        if(empty($id)){
            $this->error('参数错误');
        }
        $result=$this->model->del($id);
        $this->updateResult($result,'删除成功','dataList');
    }
}
