<?php
namespace app\admin\controller;
class Record extends Base
{
    protected $model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model=model('ReportBackup');
    }

    public function dataList()
    {
        $where=$this->buildWhere(['company','truckID:like']);
        $list=$this->model->data_list($where);
        $company=model('company')->selectList();
        $this->assign('company', $company);
        $this->assign('list', $list);
        return $this->fetch('list');
    }

    public function add(){
        if($this->request->isPost()){
            $data=input();
            $result=$this->model->add($data);
            $this->updateResult($result);
        }else{
            $company=model('company')->selectList();
            $this->assign('company', $company);
            $driver=model('Driver')->selectList();
            $this->assign('driver', $driver);
            return $this->fetch();
        }
    }

    public function edit(){
        if($this->request->isPost()){
            $data=input();
            $result=$this->model->edit($data);
            $this->updateResult($result,'保存成功','dataList');
        }else{
            $id=input('id');
            $data=$this->model->getOne($id);
            if(!$data){
                $this->error($this->model->getError());
            }
            $company=model('company')->selectList();
            $this->assign('company', $company);
            $driver=model('Driver')->selectList();
            $this->assign('driver', $driver);
            $this->assign('data', $data);
            return $this->fetch();
        }
    }

    public function del($id=''){
        if(empty($id)){
            $this->error('参数错误');
        }
        $result=$this->model->del($id);
        $this->updateResult($result,'删除成功','dataList');
    }
}
